USE [master]
GO

/****** Object:  Database [SweeftAssignment]    Script Date: 9/28/2023 1:15:58 PM ******/
CREATE DATABASE [SweeftAssignment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SweeftAssignment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SweeftAssignment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SweeftAssignment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SweeftAssignment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SweeftAssignment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SweeftAssignment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SweeftAssignment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SweeftAssignment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SweeftAssignment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SweeftAssignment] SET ARITHABORT OFF 
GO

ALTER DATABASE [SweeftAssignment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SweeftAssignment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SweeftAssignment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SweeftAssignment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SweeftAssignment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SweeftAssignment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SweeftAssignment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SweeftAssignment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SweeftAssignment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SweeftAssignment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SweeftAssignment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SweeftAssignment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SweeftAssignment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SweeftAssignment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SweeftAssignment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SweeftAssignment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SweeftAssignment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SweeftAssignment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SweeftAssignment] SET  MULTI_USER 
GO

ALTER DATABASE [SweeftAssignment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SweeftAssignment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SweeftAssignment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SweeftAssignment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SweeftAssignment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SweeftAssignment] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SweeftAssignment] SET  READ_WRITE 
GO


